-- =============================================================================
-- PERF_LAB Setup — Script 02 of 7
-- 02_create_tables.sql
--
-- Purpose: create all 10 PERF_LAB tables — an order-processing/payments
-- application schema — with realistic columns, primary keys, foreign
-- keys, and the two partitioned tables (ORDERS, SALES) the course design
-- calls for.
--
-- Run connected AS perf_lab (created by 01_create_user.sql):
--   sqlplus perf_lab/<password>@//localhost:1521/PERFPDB @02_create_tables.sql
--
-- This script assumes a clean, empty PERF_LAB schema (freshly created by
-- 01_create_user.sql). It does not attempt to be idempotent/re-runnable
-- against a schema that already has these objects — to rebuild from
-- scratch, drop and recreate the PERF_LAB user first.
--
-- INDEX PHILOSOPHY (read before 03_create_indexes.sql):
-- Every PRIMARY KEY / UNIQUE constraint below creates its own supporting
-- unique index automatically as part of this script — that is unavoidable
-- Oracle behavior, not a tuning decision. Beyond that, this script and
-- 03_create_indexes.sql deliberately do NOT add indexes on foreign-key
-- columns (e.g. ORDER_ITEMS.PRODUCT_ID, ORDERS.CUSTOMER_ID). That gap is
-- intentional: several days in this course (Day 2's investigation demo,
-- Day 23's indexing-strategy lab, among others) exist specifically to
-- teach students to diagnose and fix the consequences of an unindexed
-- foreign key. See 03_create_indexes.sql for the full rationale.
--
-- SURROGATE KEYS: every table's primary key is an IDENTITY column
-- (GENERATED BY DEFAULT ON NULL AS IDENTITY). "BY DEFAULT ON NULL" (as
-- opposed to "ALWAYS") is deliberate: it lets 04_generate_data.sql supply
-- explicit, densely-packed key values for fast bulk loading, while still
-- allowing ordinary single-row INSERTs in later days' demos to omit the
-- key and get one generated automatically. 04_generate_data.sql reseeds
-- each identity generator's next value after the bulk load completes
-- (ALTER TABLE ... MODIFY ... GENERATED ... START WITH LIMIT VALUE) so
-- those later single-row inserts don't collide with bulk-loaded IDs.
-- =============================================================================

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT
PROMPT ================================================================================
PROMPT  PERF_LAB Setup — Step 2: create tables
PROMPT ================================================================================
PROMPT

-- =============================================================================
-- 1. DEPARTMENTS (org structure) — Standard tier: 200 rows
--
-- Created before EMPLOYEES because EMPLOYEES.DEPARTMENT_ID references it.
-- MANAGER_ID is added WITHOUT a foreign key here, on purpose: it points at
-- EMPLOYEES, which does not exist yet (a genuine circular dependency
-- between DEPARTMENTS and EMPLOYEES). The FK is added afterward, once
-- EMPLOYEES exists (see step 3 below).
-- =============================================================================
PROMPT Creating DEPARTMENTS ...

CREATE TABLE departments (
  department_id    NUMBER(6)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  department_code  VARCHAR2(10)  NOT NULL,
  department_name  VARCHAR2(100) NOT NULL,
  cost_center      VARCHAR2(20),
  location         VARCHAR2(60),
  manager_id       NUMBER(8),                     -- FK added in step 3, after EMPLOYEES exists
  created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_departments        PRIMARY KEY (department_id),
  CONSTRAINT uq_departments_code   UNIQUE (department_code)
);

-- =============================================================================
-- 2. EMPLOYEES (internal staff) — Standard tier: 10,000 rows
--
-- Self-referencing FK (manager_id -> employees.employee_id) is declared
-- inline; Oracle allows this because the constraint is validated against
-- row data, not against the table's DDL-time existence.
-- =============================================================================
PROMPT Creating EMPLOYEES ...

CREATE TABLE employees (
  employee_id      NUMBER(8)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  employee_number  VARCHAR2(20)  NOT NULL,
  first_name       VARCHAR2(50)  NOT NULL,
  last_name        VARCHAR2(50)  NOT NULL,
  email            VARCHAR2(100),
  phone            VARCHAR2(20),
  hire_date        DATE          NOT NULL,
  job_title        VARCHAR2(60),
  department_id    NUMBER(6),
  manager_id       NUMBER(8),
  salary           NUMBER(10,2),
  employee_status  VARCHAR2(15)  DEFAULT 'ACTIVE' NOT NULL,
  created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_employees            PRIMARY KEY (employee_id),
  CONSTRAINT uq_employees_number     UNIQUE (employee_number),
  CONSTRAINT fk_employees_department FOREIGN KEY (department_id) REFERENCES departments(department_id),
  CONSTRAINT fk_employees_manager    FOREIGN KEY (manager_id) REFERENCES employees(employee_id),
  CONSTRAINT ck_employees_status     CHECK (employee_status IN ('ACTIVE','ON_LEAVE','TERMINATED'))
);

-- Now that EMPLOYEES exists, add the deferred FK from DEPARTMENTS.MANAGER_ID.
ALTER TABLE departments
  ADD CONSTRAINT fk_departments_manager FOREIGN KEY (manager_id) REFERENCES employees(employee_id);

-- =============================================================================
-- 3. CUSTOMERS (customer master) — Standard tier: 500,000 rows
--
-- REGION and CUSTOMER_STATUS are deliberately skewed columns (see
-- 04_generate_data.sql for the exact skew) — they exist specifically so
-- Day 24 (Optimizer & Statistics: cardinality and histograms) has a real,
-- reproducible skewed-data cardinality-misestimation problem to diagnose.
-- Do not "fix" the skew when generating data; it is the point.
-- =============================================================================
PROMPT Creating CUSTOMERS ...

CREATE TABLE customers (
  customer_id       NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_number   VARCHAR2(20)  NOT NULL,
  first_name        VARCHAR2(50)  NOT NULL,
  last_name         VARCHAR2(50)  NOT NULL,
  email             VARCHAR2(100),
  phone             VARCHAR2(20),
  address_line1     VARCHAR2(100),
  address_line2     VARCHAR2(100),
  city              VARCHAR2(60),
  state_province    VARCHAR2(60),
  postal_code       VARCHAR2(20),
  country_code      CHAR(2)       DEFAULT 'US' NOT NULL,
  region            VARCHAR2(20)  NOT NULL,   -- deliberately skewed: see 04_generate_data.sql
  customer_status   VARCHAR2(15)  NOT NULL,   -- deliberately skewed: see 04_generate_data.sql
  customer_type     VARCHAR2(15)  DEFAULT 'RETAIL' NOT NULL,
  credit_limit      NUMBER(12,2)  DEFAULT 0,
  date_registered   DATE          DEFAULT SYSDATE NOT NULL,
  last_order_date   DATE,
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_customers          PRIMARY KEY (customer_id),
  CONSTRAINT uq_customers_number   UNIQUE (customer_number),
  CONSTRAINT ck_customers_status   CHECK (customer_status IN ('ACTIVE','INACTIVE','SUSPENDED','CLOSED')),
  CONSTRAINT ck_customers_type     CHECK (customer_type IN ('RETAIL','WHOLESALE','VIP'))
);

-- =============================================================================
-- 4. PRODUCTS (product catalog) — Standard tier: 50,000 rows
--
-- PRODUCT_NAME is the function-based-index candidate the course design
-- calls for: Day 23 builds an index on UPPER(product_name) to support
-- case-insensitive lookups without a wrapper column. No extra stored
-- column is needed for that — the function-based index is built directly
-- against this column when that day introduces it.
-- =============================================================================
PROMPT Creating PRODUCTS ...

CREATE TABLE products (
  product_id        NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  product_sku       VARCHAR2(30)  NOT NULL,
  product_name      VARCHAR2(150) NOT NULL,   -- function-based index candidate: UPPER(product_name), Day 23
  category          VARCHAR2(50),
  subcategory       VARCHAR2(50),
  brand             VARCHAR2(50),
  unit_price        NUMBER(10,2)  NOT NULL,
  unit_cost         NUMBER(10,2),
  product_status    VARCHAR2(15)  DEFAULT 'ACTIVE' NOT NULL,
  is_discontinued   CHAR(1)       DEFAULT 'N' NOT NULL,
  weight_kg         NUMBER(8,3),
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_products          PRIMARY KEY (product_id),
  CONSTRAINT uq_products_sku      UNIQUE (product_sku),
  CONSTRAINT ck_products_status   CHECK (product_status IN ('ACTIVE','DISCONTINUED','OUT_OF_STOCK')),
  CONSTRAINT ck_products_discont  CHECK (is_discontinued IN ('Y','N'))
);

-- =============================================================================
-- 5. ORDERS (order headers) — Standard tier: 5,000,000 rows
--    RANGE PARTITIONED BY ORDER_DATE, monthly, via INTERVAL partitioning.
--
-- INTERVAL partitioning (11g+) is used instead of hand-listing ~24 monthly
-- partitions: one explicit starting partition defines the transition
-- point, and Oracle creates each subsequent monthly partition
-- automatically the first time a row needs it. 04_generate_data.sql
-- generates ORDER_DATE values across roughly a 2-year window starting at
-- the boundary below, which yields the ~24 monthly partitions the course
-- design calls for.
--
-- ENVIRONMENT DEPENDENT / instructor note: the date window below
-- (2024-01-01 onward) is a fixed training window, not tied to "today."
-- Adjust the starting boundary if you want the lab data to read as
-- current relative to when you are actually running the course — just
-- keep ORDERS and SALES (step 9) using the SAME starting boundary, since
-- Day 27's partition-wise join demo depends on both tables' monthly
-- partitions being aligned.
--
-- PRIMARY KEY INDEX: ORDER_ID is a surrogate key unrelated to ORDER_DATE,
-- so its PK constraint creates a single GLOBAL (non-partitioned) unique
-- index by default — this is standard, unavoidable Oracle behavior for a
-- unique/PK constraint on a partitioned table whose key isn't a superset
-- of the partition key. That tradeoff (a global index needs its own
-- maintenance on partition operations such as DROP/EXCHANGE PARTITION)
-- is exactly what Day 27 discusses.
-- =============================================================================
PROMPT Creating ORDERS (interval-partitioned by ORDER_DATE) ...

CREATE TABLE orders (
  order_id                NUMBER(12)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id             NUMBER(10)     NOT NULL,
  order_date              DATE           NOT NULL,   -- partition key
  order_status            VARCHAR2(20)   NOT NULL,
  order_channel           VARCHAR2(20)   DEFAULT 'WEB' NOT NULL,
  ship_date               DATE,
  required_date           DATE,
  order_total             NUMBER(12,2)   NOT NULL,
  tax_amount               NUMBER(10,2)   DEFAULT 0 NOT NULL,
  shipping_amount          NUMBER(10,2)   DEFAULT 0 NOT NULL,
  discount_amount          NUMBER(10,2)   DEFAULT 0 NOT NULL,
  currency_code            CHAR(3)        DEFAULT 'USD' NOT NULL,
  payment_method           VARCHAR2(20),
  shipping_address_line1   VARCHAR2(100),
  shipping_city            VARCHAR2(60),
  shipping_state           VARCHAR2(60),
  shipping_postal_code     VARCHAR2(20),
  sales_rep_id              NUMBER(8),
  notes                     VARCHAR2(4000),
  created_at                TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_orders            PRIMARY KEY (order_id),
  CONSTRAINT fk_orders_customer   FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_orders_employee   FOREIGN KEY (sales_rep_id) REFERENCES employees(employee_id),
  CONSTRAINT ck_orders_status     CHECK (order_status IN
                                     ('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURNED')),
  CONSTRAINT ck_orders_channel    CHECK (order_channel IN ('WEB','MOBILE','STORE','PHONE'))
)
PARTITION BY RANGE (order_date)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
  PARTITION p_orders_start VALUES LESS THAN (DATE '2024-01-01')
);

-- =============================================================================
-- 6. ORDER_ITEMS (order line items) — Standard tier: 20,000,000 rows
--
-- Not partitioned (only ORDERS and SALES are, per the course design).
-- FK to ORDERS and PRODUCTS. NOTE: no supporting index is created on
-- either FK column here or in 03_create_indexes.sql — see the index
-- philosophy note at the top of this file. ORDER_ITEMS.PRODUCT_ID being
-- unindexed is the specific, deliberate root cause of the Day 2 demo.
-- =============================================================================
PROMPT Creating ORDER_ITEMS ...

CREATE TABLE order_items (
  order_item_id   NUMBER(14)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id        NUMBER(12)    NOT NULL,
  product_id      NUMBER(10)    NOT NULL,
  line_number     NUMBER(4)     NOT NULL,
  quantity        NUMBER(8)     NOT NULL,
  unit_price      NUMBER(10,2)  NOT NULL,
  discount_pct    NUMBER(5,2)   DEFAULT 0 NOT NULL,
  line_total      NUMBER(12,2)  NOT NULL,
  tax_amount      NUMBER(10,2)  DEFAULT 0 NOT NULL,
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_order_items        PRIMARY KEY (order_item_id),
  CONSTRAINT fk_order_items_order  FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_order_items_prod   FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- =============================================================================
-- 7. PAYMENTS (payment transactions) — Standard tier: 5,000,000 rows
--
-- FK to ORDERS. Also the hot-block/contention demo target for Day 31.
-- NOTE: this table intentionally has NO payment_method column at baseline
-- — Day 2's lab adds PAYMENT_METHOD via ALTER TABLE as part of its own
-- demo narrative ("a column shipped without an index"). Do not add it
-- here; doing so would remove the very column Day 2 is designed to add.
-- =============================================================================
PROMPT Creating PAYMENTS ...

CREATE TABLE payments (
  payment_id           NUMBER(12)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id             NUMBER(12)    NOT NULL,
  payment_date         DATE          NOT NULL,
  payment_status       VARCHAR2(15)  NOT NULL,
  amount               NUMBER(12,2)  NOT NULL,
  currency_code        CHAR(3)       DEFAULT 'USD' NOT NULL,
  card_last4           CHAR(4),
  authorization_code   VARCHAR2(20),
  gateway_reference     VARCHAR2(50),
  processed_at          TIMESTAMP,
  created_at             TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_payments          PRIMARY KEY (payment_id),
  CONSTRAINT fk_payments_order    FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT ck_payments_status   CHECK (payment_status IN
                                     ('PENDING','AUTHORIZED','CAPTURED','FAILED','REFUNDED','VOIDED'))
);

-- =============================================================================
-- 8. TRANSACTIONS (general-ledger-style transaction log) — Standard tier: 10,000,000 rows
--
-- Deliberately NOT foreign-keyed to ORDERS/PAYMENTS: REFERENCE_TYPE +
-- REFERENCE_ID is a loose, polymorphic pointer (a common, real-world
-- general-ledger pattern — one GL log feeding from many different source
-- systems/tables). Enforcing a single FK here would misrepresent how
-- these tables actually relate in practice, so it is intentionally
-- omitted rather than an oversight. High-volume I/O and TEMP-spill demo
-- source for Days 29-30.
-- =============================================================================
PROMPT Creating TRANSACTIONS ...

CREATE TABLE transactions (
  transaction_id     NUMBER(14)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  transaction_date   DATE          NOT NULL,
  transaction_type   VARCHAR2(20)  NOT NULL,
  account_id         NUMBER(10)    NOT NULL,
  reference_type     VARCHAR2(20),          -- 'ORDER' / 'PAYMENT' / 'MANUAL' / 'SYSTEM' — no enforced FK, see above
  reference_id       NUMBER(14),
  amount             NUMBER(14,2)  NOT NULL,
  currency_code      CHAR(3)       DEFAULT 'USD' NOT NULL,
  gl_account_code    VARCHAR2(20),
  description        VARCHAR2(200),
  posted_by          VARCHAR2(30)  DEFAULT USER NOT NULL,
  created_at         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_transactions       PRIMARY KEY (transaction_id),
  CONSTRAINT ck_transactions_type  CHECK (transaction_type IN ('DEBIT','CREDIT','ADJUSTMENT','FEE','REFUND'))
);

-- =============================================================================
-- 9. SALES (aggregated sales facts) — Standard tier: 10,000,000 rows
--    RANGE PARTITIONED BY SALE_DATE, monthly, via INTERVAL partitioning —
--    the SAME starting boundary as ORDERS (step 5), so Day 27 can
--    demonstrate a partition-wise join between the two.
--
-- FK to PRODUCTS and CUSTOMERS (typical star-schema fact-to-dimension
-- pattern). ORDER_ID is a loose reference back to the originating order,
-- deliberately NOT foreign-keyed — SALES is an aggregated/derived fact
-- table, and real data-warehouse fact tables commonly do not enforce FKs
-- back to the transactional source system that fed them.
-- =============================================================================
PROMPT Creating SALES (interval-partitioned by SALE_DATE) ...

CREATE TABLE sales (
  sale_id         NUMBER(14)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  sale_date       DATE          NOT NULL,   -- partition key; aligned with ORDERS.ORDER_DATE boundaries
  product_id      NUMBER(10)    NOT NULL,
  customer_id     NUMBER(10),
  region          VARCHAR2(20),
  quantity_sold   NUMBER(10)    NOT NULL,
  unit_price      NUMBER(10,2)  NOT NULL,
  total_amount    NUMBER(14,2)  NOT NULL,
  order_id        NUMBER(12),                -- loose reference to ORDERS; intentionally not FK-enforced, see above
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_sales           PRIMARY KEY (sale_id),
  CONSTRAINT fk_sales_product   FOREIGN KEY (product_id) REFERENCES products(product_id),
  CONSTRAINT fk_sales_customer  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
)
PARTITION BY RANGE (sale_date)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
  PARTITION p_sales_start VALUES LESS THAN (DATE '2024-01-01')
);

-- =============================================================================
-- 10. LOG_EVENTS (application/event log) — Standard tier: 20,000,000 rows
--
-- Insert-heavy design, deliberately: LOG_ID is a plain monotonically
-- increasing surrogate key, which is a well-known real-world anti-pattern
-- under heavy concurrent insert load (every session's next insert
-- competes for the same "right-hand" leaf block of the primary-key
-- index — index/buffer hot-block contention). This is left exactly as a
-- typical, unremarkable-looking table would be built, on purpose: it is
-- the deliberate setup for Day 31's concurrency/hot-block demo (and, more
-- generally, Day 17's redo/log-sync demo under insert load). Do not
-- "improve" this design (e.g. with a reverse-key index) here — Day 31
-- teaches that fix as part of diagnosing the problem it causes.
--
-- No foreign keys: log/event tables in real systems are routinely
-- decoupled from the OLTP schema on purpose (so logging never blocks on,
-- or is blocked by, application-table locking, and so the log survives
-- even if the referenced business row is later purged/archived).
--
-- EVENT_DETAIL is a VARCHAR2, not a CLOB: a 20-million-row CLOB column
-- would meaningfully complicate bulk generation (LOB space management,
-- much larger storage/redo footprint) without adding teaching value this
-- course's days actually use — kept as VARCHAR2 deliberately.
-- =============================================================================
PROMPT Creating LOG_EVENTS ...

CREATE TABLE log_events (
  log_id           NUMBER(14)     GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- deliberate monotonic PK; see note above
  log_timestamp    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  event_type       VARCHAR2(30)   NOT NULL,
  event_source     VARCHAR2(50),
  severity         VARCHAR2(10)   DEFAULT 'INFO' NOT NULL,
  session_id       VARCHAR2(50),
  user_id          NUMBER(10),         -- loosely related to CUSTOMERS/EMPLOYEES; intentionally not FK-enforced
  host_name        VARCHAR2(60),
  message          VARCHAR2(500),
  event_detail     VARCHAR2(4000),
  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_log_events       PRIMARY KEY (log_id),
  CONSTRAINT ck_log_events_sev   CHECK (severity IN ('DEBUG','INFO','WARN','ERROR','FATAL'))
);

PROMPT
PROMPT ---- Verifying: table count ----
SELECT COUNT(*) AS tables_created FROM user_tables;

PROMPT
PROMPT ---- Verifying: constraint count by type ----
COLUMN constraint_type FORMAT A20
SELECT CASE constraint_type
         WHEN 'P' THEN 'PRIMARY KEY'
         WHEN 'R' THEN 'FOREIGN KEY'
         WHEN 'U' THEN 'UNIQUE'
         WHEN 'C' THEN 'CHECK'
         ELSE constraint_type
       END AS constraint_type,
       COUNT(*) AS cnt
FROM   user_constraints
WHERE  constraint_type IN ('P','R','U','C')
GROUP  BY constraint_type
ORDER  BY constraint_type;

PROMPT
PROMPT ---- Verifying: partitioned tables ----
SELECT table_name, partitioning_type, interval
FROM   user_part_tables
ORDER  BY table_name;

PROMPT
PROMPT ================================================================================
PROMPT  All 10 PERF_LAB tables created.
PROMPT  Next step: 03_create_indexes.sql
PROMPT ================================================================================
PROMPT
